version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce

  sonarqubedb:
    image: postgres:alpine
  
  sonarqube:
    image: sonarqube:community

  mongo-express:
    image: mongo-express

  mongodb:
    image: mongo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

  rabbitmq:
    image: rabbitmq:3-management-alpine

  grafana:
    image: grafana/grafana

  prometheus:
    image: prom/prometheus

  jaeger: 
    image: jaegertracing/all-in-one:latest

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    container_name: catalogApi
    build:
      context: ..
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  portainer_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  mongo_data:
  elasticsearch_data:
  grafana_data:
  prometheus_data:

networks: 
  catalog-network:
    driver: bridge
  elastic-network:
    driver: bridge
  prometheus-network:
    driver: bridge
