global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
- job_name: 'CatalogAPI'
  static_configs:
  - targets: ['catalogApi:80']
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080  